  version: '3'
  services:
    app:
      image: amazonlinux
      command: python main.py

    dynamodb:
      image: cnadiminti/dynamodb-local

    dynamodb-gui:
      image: yamitzky/dynamodb-gui
      environment:
        - AWS_ACCESS_KEY_ID=dummy
        - AWS_SECRET_ACCESS_KEY=dummy
        - DYNAMO_ENDPOINT=http://dynamodb:8000
      links:
        - dynamodb
      ports:
        - 8001:8001
